- type: script
  typeLabel: 代码编辑器
  name: Python脚本编辑器
  key: ExecutePythonScript
  supportConfigInPorts: True
  supportConfigOutPorts: True
  helpUrl:
  parameters:
    - key: script
      name: Python脚本
      type: inputPythonScript
      required: True
      default: "# 输入端口数据通过inputs[n]来引用n从0开始:\n#   输处端口数据放入outputs，outputs为元组或列表\n#   outputs = (int(inputs[0])+1, )\n"
    - key: inPorts
      name: 输入端口
      type: ports
      default:
        - id: "in1"
          name: "in1"
    - key: outPorts
      name: 输出端口
      type: ports
      default:
        - id: "out1"
          name: "out1"
