- type: process
  typeLabel: 逻辑处理
  name: 数据同步
  key: DataSync
  supportConfigInPorts: True
  supportConfigOutPorts: True
  helpUrl:
  parameters:
    - key: empty
      name: 同步后清空端口数据
      type: checkbox
      required: True
      default: True
    - key: triggerPort
      name: 触发端口
      type: inputString
      default: ""
    - key: inPorts
      name: 输入端口
      type: ports
      default:
        - id: "in1"
          name: "in1"
    - key: outPorts
      name: 输出端口
      type: ports
      default:
        - id: "out1"
          name: "out1"
