- type: process
  typeLabel: 逻辑处理
  name: 数据同步
  key: DataSync
  supportConfigInPorts: True
  supportConfigOutPorts: True
  helpUrl:
  parameters:
    - key: empty
      name: 同步后清空端口数据
      type: checkbox
      required: True
      default: True
    - key: triggerPort
      name: 触发端口
      type: inputString
      default: ""
    - key: inPorts
      name: 输入端口
      type: ports
      default:
        - id: "in1"
          name: "in1"
    - key: outPorts
      name: 输出端口
      type: ports
      default:
        - id: "out1"
          name: "out1"
- type: process
  typeLabel: 逻辑处理
  name: 全局变量设置
  key: GlobalVariableSetter
  helpUrl:
  parameters:
    - key: name
      name: 变量名称
      type: inputString
      required: True
      default: ""
  ports:
    in:
      - id: in1
        name: in1
    out:
      - id: out1
        name: out1
- type: process
  typeLabel: 逻辑处理
  name: 全局变量获取
  key: GlobalVariableGetter
  helpUrl:
  parameters:
    - key: name
      name: 变量名称
      type: inputString
      required: True
      default: ""
  ports:
    in:
      - id: in1
        name: in1
    out:
      - id: out1
        name: out1
- type: process
  typeLabel: 逻辑处理
  name: 全局变量清除
  key: GlobalVariableDeleter
  helpUrl:
  parameters:
    - key: name
      name: 变量名称
      type: inputString
      required: True
      default: ""
  ports:
    in:
      - id: in1
        name: in1
    out:
      - id: out1
        name: out1