- type: database
  typeLabel: 数据库
  category: read
  categoryLabel: 数据库读取
  name: Mysql数据库读取
  key: MysqlReader
  helpUrl:
  parameters:
    - key: host
      name: 主机名或IP地址
      type: inputString
      required: True
      default: ""
    - key: port
      name: 端口
      type: inputString
      required: True
      default: ""
    - key: user
      name: 用户名
      type: inputString
      required: True
      default: ""
    - key: password
      name: 密码
      type: inputString
      required: True
      default: ""
    - key: dbname
      name: 数据库
      type: inputString
      required: True
      default: ""
    - key: table
      name: 表名
      type: inputString
      default: ""
    - key: sql
      name: sql
      type: inputString
      default: ""
  ports:
    in:
      - id: in1
        name: in1
    out:
      - id: out1
        name: out1

- type: database
  typeLabel: 数据库
  category: execute
  categoryLabel: 数据库执行
  name: Mysql数据库执行sql
  key: MysqlExecutor
  helpUrl:
  parameters:
    - key: host
      name: 主机名或IP地址
      type: inputString
      required: True
      default: ""
    - key: port
      name: 端口
      type: inputString
      required: True
      default: ""
    - key: user
      name: 用户名
      type: inputString
      required: True
      default: ""
    - key: password
      name: 密码
      type: inputString
      required: True
      default: ""
    - key: dbname
      name: 数据库
      type: inputString
      required: True
      default: ""
    - key: sql
      name: sql执行语句
      type: inputString
      default: ""
  ports:
    in:
      - id: in1
        name: in1
    out:
      - id: out1
        name: out1

- type: database
  typeLabel: 数据库
  category: write
  categoryLabel: 数据库写入
  name: Mysql数据库写入
  key: MysqlWriter
  helpUrl:
  parameters:
    - key: host
      name: 主机名或IP地址
      type: inputString
      required: True
      default: ""
    - key: port
      name: 端口
      type: inputString
      required: True
      default: ""
    - key: user
      name: 用户名
      type: inputString
      required: True
      default: ""
    - key: password
      name: 密码
      type: inputString
      required: True
      default: ""
    - key: dbname
      name: 数据库
      type: inputString
      required: True
      default: ""
    - key: table
      name: 写入表名
      type: inputString
      required: True
    - key: mode
      name: 写入方式
      options:
        - value: append
          label: 追加
        - value: replace
          label: 覆盖
        - value: clearAndAppend
          label: 清空并追加
      type: select
      default: clearAndAppend
    - key: chunksize
      name: 每次写入最大行数
      type: inputString
      default: "1000"
  ports:
    in:
      - id: in1
        name: in1
    out:
      - id: out1
        name: out1
